version: "3"
services:
    alkoholcz_www:
        container_name: alkoholcz_apache
        build: .
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ../:/var/www/html/
        links:
            - alkoholcz_db
        networks:
            - default
    alkoholcz_db:
        image: mysql
        cap_add:
            - SYS_NICE  # CAP_SYS_NICE
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: alkoholcz
            MYSQL_USER: alkoholcz
            MYSQL_PASSWORD: alkoholcz
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - alkoholcz_persistent:/var/lib/mysql
        command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci', '--default-authentication-plugin=mysql_native_password']
        networks:
            - default
    adminer:
        image: adminer:latest
        links:
            - alkoholcz_db:db
        ports:
            - 8081:8080
volumes:
    alkoholcz_persistent:
